PinnaFace.Web/Controllers/ComplainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using PinnaFace.Core;
using PinnaFace.Core.Enumerations;
using PinnaFace.Core.Models;
using PinnaFace.Service;
using PinnaFace.Service.Interfaces;
using PinnaFace.Web.Models;
using WebMatrix.WebData;

namespace PinnaFace.Web.Controllers
{
    [Authorize]
    public class ComplainController : Controller
    {
        private readonly IComplainService _complainService;
        
        public ComplainController()
        {
            LoadEnums();
            _complainService = new ComplainService();
        }

        public ActionResult Index(string searchText, int? page, int? pageSize, int? ptype, int? processStatusId)
        {
            var criteria = new SearchCriteria<ComplainDTO>
            {
                CurrentUserId = WebSecurity.CurrentUserId
            };

            @ViewData["processStatusId"] = processStatusId;
            if (processStatusId != null && processStatusId > -1)
            {
                var compStatus = (ComplainStatusTypes) processStatusId;
                criteria.FiList.Add(p => p.Status == compStatus);

                @ViewData["ComplainStatusHeader"] = compStatus;
            }
            else if (processStatusId == -1)
            {
                @ViewData["ComplainStatusHeader"] = "All";    
            }
            else if (processStatusId == null)
            {
                criteria.FiList.Add(p => p.Status == ComplainStatusTypes.Opened ||
                                            p.Status == ComplainStatusTypes.ReOpened ||
                                            p.Status == ComplainStatusTypes.OnProcess);
                @ViewData["ComplainStatusHeader"] = "New/Reopened/OnProcess";
            }
            #region Search Text
            if (!string.IsNullOrEmpty(searchText))
            {
                ViewData["ItemSearch"] = "search results for '<strong style='font-size:14px;'>" + searchText + "</strong>'";
                ViewData["SearchText"] = searchText;
                ViewData["ItemSearchHidden"] = "visible";
            }
            else
            {
                ViewData["ItemSearch"] = string.Empty;
                ViewData["SearchText"] = string.Empty;
                ViewData["ItemSearchHidden"] = "hidden";
            }

            if (!string.IsNullOrEmpty(searchText))
                criteria.FiList.Add(bp => bp.Complain.ToLower().Contains(searchText.ToLower()) ||
                                    bp.RaisedByName.ToLower().Contains(searchText.ToLower()));
            #endregion

            #region Paging
            if (page != null && ptype != null && pageSize != null)
            {
                criteria.Page = (int)(page + ptype);
                criteria.PageSize = (int)pageSize;

                if (criteria.Page < 1)
                    criteria.Page = 1;
            }
            else
            {
                criteria.Page = 1;
                criteria.PageSize = 10;
            }
            if (criteria.Page == 1)
                ViewData["prevDisabled"] = "none";
            ViewData["Page"] = criteria.Page;
            ViewData["PageSize"] = criteria.PageSize;

            #endregion

            int totalCount;
            var complains = _complainService.GetAll(criteria, out totalCount);
            @ViewData["totalNumber"] = totalCount;


            #region Paging
            var pages = HelperUtility.GetPages(totalCount, criteria.PageSize);
            ViewData["totalPages"] = pages;

            if (pages == 0)
            {
                criteria.Page = 0;
                ViewData["Page"] = 0;
            }

            if (criteria.Page == pages)
                ViewData["nextDisabled"] = "none";

            #endregion

            #region For Serial Number
            var sNo = (criteria.Page - 1) * criteria.PageSize + 1;
            foreach (var complainDTO in complains)
            {
                complainDTO.SerialNumber = sNo;
                sNo++;
            }
            #endregion


            if (Request.IsAjaxRequest())
            {
                if (!Request.IsAuthenticated)
                    Redirect("~/Account/Login");
                return PartialView("_complain", complains);
            }
            return View(complains);
        }

        
        public ActionResult Details(string compId)
        {
            int complainId = EncryptionUtility.Hash64Decode(compId);
            var complainDTO = new ComplainDTO
            {
                Employee = new EmployeeDTO()
            };
            if (complainId != 0)
            complainDTO = new ComplainService(true)
                .GetAll()
                .ToList()
                .FirstOrDefault(v => v.Id == complainId );
            return View(complainDTO);
        }
        

        public ActionResult Create(string empId, string searchText)
        {
            bool employeefound = false;
            var complainDTO = new ComplainDTO
            {
                AgencyId = Singleton.Agency.Id,
                ComplainDate = DateTime.Now,
                Priority = ComplainProrityTypes.Medium,
                Type = ComplainTypes.StatusNotKnown
            };

            if (!string.IsNullOrEmpty(empId))
            {
                int employeeId = EncryptionUtility.Hash64Decode(empId);
                var employee = new EmployeeService(true, true)
                    .GetAll().ToList()
                    .FirstOrDefault(v => v.Id == employeeId);
                employeefound = true;

                complainDTO.EmployeeId = employeeId;
                complainDTO.Employee = employee;
                complainDTO.Complain = "...";
            }
            else if (!string.IsNullOrEmpty(searchText))
            {
                var criteria = new SearchCriteria<EmployeeDTO>();
                if (!string.IsNullOrEmpty(searchText))
                    criteria.FiList.Add(bp => bp.Visa != null &&
                                              bp.Visa.Sponsor != null &&
                                              bp.CurrentStatus == ProcessStatusTypes.OnGoodCondition &&
                                              (bp.FullName.ToLower().Contains(searchText.ToLower()) ||
                                               bp.PassportNumber.ToLower().Contains(searchText.ToLower()) ||
                                               bp.Visa.Sponsor.PassportNumber.ToLower().Contains(searchText.ToLower()) ||
                                               bp.Visa.Sponsor.FullName.ToLower().Contains(searchText.ToLower()) ||
                                               bp.MoreNotes.ToLower().Contains(searchText.ToLower())));

                var employee = new EmployeeService(true, true)
                    .GetAll(criteria).ToList().FirstOrDefault();

                if (employee != null)
                {
                    employeefound = true;
                    complainDTO.EmployeeId = employee.Id;
                    complainDTO.Employee = employee;
                    complainDTO.Complain = "...";
                }
            }



            if (Request.IsAjaxRequest())
            {
                if (!Request.IsAuthenticated)
                    Redirect("~/Account/Login");

                if (!employeefound)
                complainDTO.Complain = "No Employee/Visa is found, please try your search again...";
            
                return PartialView("_employeeVisaShortDetail", complainDTO);
            }

            return View(complainDTO);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ComplainDTO complainDTO)
        {
            //try{}catch{}
                if (ModelState.IsValid)
                {
                    if (complainDTO.EmployeeId == 0)
                        return RedirectToAction("Create");
                    
                    var empService = new EmployeeService();
                    var emp=empService.Find(complainDTO.EmployeeId.ToString());
                    emp.Complains.Add(complainDTO);
                    emp.CurrentComplain = complainDTO;
                    //emp.CurrentStatus=ProcessStatusTypes.WithComplain;
                    empService.InsertOrUpdate(emp);
                    empService.Dispose();
                    
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("", "The user name or password provided is incorrect.");
                return View(complainDTO);
            
        }
        

        public ActionResult AddRemark(string compId)
        {
            int complainId = EncryptionUtility.Hash64Decode(compId);
            var complainRemarkDTO = new ComplainRemarkDTO
            {
                AgencyId = Singleton.Agency.Id,
                Complain = new ComplainDTO()
            };
            if (complainId != 0)
            {
                var complainDTO = new ComplainService(true)
                    .GetAll()
                    .ToList()
                    .FirstOrDefault(v => v.Id == complainId);

                if (complainDTO != null)
                {
                    complainRemarkDTO.Complain = complainDTO;
                    complainRemarkDTO.ComplainId = complainDTO.Id;
                    complainRemarkDTO.Complain.Remarks =
                        complainDTO.Remarks.OrderByDescending(c => c.RemarkDate).ToList();
                    complainRemarkDTO.RemarkDate = DateTime.Now;
                }
                else
                {
                    return RedirectToAction("Index");
                }
                
            }
            return View(complainRemarkDTO);
            
        }
        [HttpPost]
        public ActionResult AddRemark(ComplainRemarkDTO complainRemarkDTO)
        {
            try
            {
                var complainService = new ComplainService(false);

PinnaFace.Web/Views/Shared/CompanyHeader.cshtml
@model PinnaFace.Web.Models.UserCompanyDetail
@{
   
    string imagePath = "/Images/pinnafaceLogo2.jpg";
}

@if (!string.IsNullOrEmpty(@Model.HeaderUrl))// && !string.IsNullOrEmpty(@Model.Photo.AttachmentUrl))
{
    imagePath = "../Content/Images/" + @Model.HeaderUrl;
}


@if (Request.IsAuthenticated)
{
    <div style="text-align: center;">
        <h4 style="font-size: 24px; font-weight: bold; color: orange; font-family: 'Bookman Old Style';">
             <img src="@Url.Content(imagePath)" alt="Photo" id="shortPhoto" onError="this.onerror=null;this.src='/images/pinnafaceLogo2.png';" style="border-radius: 10px; height: 100px; width: 100%;" />
             <i><b>@Model.CompanyName</b></i>
        </h4>
    </div>

}

PinnaFace.Web/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "NotFound";
}

<hgroup class="title" style="margin-top:40px; ">
    <h3 class="error">Error.</h3><br/>
    <h4>Sorry, The Page, You are Looking for is not found.</h4><br/>

    <h5>@Html.ActionLink("Go Back To Home Page", "Index", "Home")</h5>  
</hgroup>
 

PinnaFace.Web/Views/Shared/_Layout.cshtml
@using Microsoft.Ajax.Utilities
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta charset="utf-8" />
    <title>PinnaFace - @ViewBag.Title</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @{
        Html.RenderPartial("~/Views/Shared/EditorTemplates/Headers.cshtml");}
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-27776013-2"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-27776013-2');
    </script>
    <style type="text/css">
        i {
        color: orange;
        }

        .navbar-inverse {
        background-color: green;
        border-color: green;
        }

        .navbar-inverse .navbar-nav>li>a {
        color: white;
        }

        .navbar-inverse .navbar-nav>.active>a,
        .navbar-inverse .navbar-nav>.active>a:hover,
        .navbar-inverse .navbar-nav>.active>a:focus {
        color: #ffffff;
        background-color: darkgreen;
        }

        .navbar-inverse .navbar-nav>.open>a,
        .navbar-inverse .navbar-nav>.open>a:hover,
        .navbar-inverse .navbar-nav>.open>a:focus {
        color: #ffffff;
        background-color: mediumseagreen;
        }

        h1,
        h2,
        h3,
        h4,
        h5,
        h6 {
        color: orange;
        margin-bottom: 0;
        padding-bottom: 0;
        }
    </style>

</head>

<body>
    <div id="wrap">
        <div class="navbar-wrapper">
            <div class="container">

                <div class="navbar navbar-inverse navbar-default navbar-fixed-top " role="navigation">
                    <div class="container">
                        <div class="navbar-header ">
                            <button type="button" class="navbar-toggle" data-toggle="collapse"
                            data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            @*<img src="@Url.Content("../Images/pinnafaceLogo.png")" alt="Photo"
                                style="border-radius: 5px; height: 60px; width: 100px;"/>*@
                            <a class="navbar-brand" href="~/Home" style="font-size: 32px; font-weight: bold; 
                            color: white; font-family: 'Cooper Black';">
                                PF
                            </a>
                        </div>
                        <div class="navbar-collapse collapse navbar-right">

                            @Html.Action("_LoginPartial","Home")

                        </div>
                    </div>
                </div>


            </div>
        </div>

        <section class="content-wrapper main-content clear-fix container">
            @Html.Action("CompanyHeader","Home")

            @RenderBody()
        </section>
    </div>

    <div id="footer">
        <div class="container">
            <p class="text-muted" style="text-align: right;">&copy; Copyright 2019 <a href="http://www.pinnasofts.com"
                target="_blank">Pinnacle Software PLC</a>
                @*&middot; <a href="#" class="hidden-print">Privacy</a> &middot; <a href="#"
                    class="hidden-print">Terms</a>*@
            </p>
        </div>
    </div>

    <script type="text/javascript">
        $('.dropdown-toggle').dropdown();
        $(".collapse").collapse();

        function error_handler(e) {
        if (e.errors) {
        var message = "Errors:\n";
        $.each(e.errors, function (key, value) {
        if ('errors' in value) {
        $.each(value.errors, function () {
        message += this + "\n";
        });
        }
        });
        alert(message);
        }
        }

        //function() { return $("input[name='religion_id']").eq(1).val(); };
    </script>
</body>

</html>

PinnaFace.Web/Views/Shared/_complain.cshtml
@using PinnaFace.Core.Enumerations
@model IEnumerable<PinnaFace.Core.Models.ComplainDTO>
<div id="table_id">
    <div id="spinner">
    </div>

    @*<div>
        <span>@ViewData["ItemSearch"]</span>
    </div>*@
    
    <div class="alert alert-info fade in @ViewData["ItemSearchHidden"]">
        <button type="button" class="close" data-dismiss="alert">×</button>
        @MvcHtmlString.Create(@ViewData["ItemSearch"].ToString())
    </div>

    <div>
        <h4 style="margin-top: 3px;">@ViewData["ComplainStatusHeader"] Complains</h4> 
        <p> (@ViewData["totalNumber"]) Complains(s) found</p>
    </div>

    <table class="table table-striped table-condensed table-hover " id="table_id2">

        <tr>
            <th>@Html.DisplayNameFor(model => model.SerialNumber)
            </th>
            @*<th>Number
            </th>*@
            <th>Employee Name
            </th>
            <th>Sponsor Name
            </th>
           @* <th>Sponsor Mobile
            </th>*@
            <th>Days Passed
            </th>
            <th>@Html.DisplayNameFor(model => model.Type)
            </th>
            <th>@Html.DisplayNameFor(model => model.Status)
            </th>
           
            <th style="text-align: center; width: 350px;" class="hidden-print"></th>
        </tr>

        <tbody>
            @foreach (var complainDTO in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => complainDTO.SerialNumber)
                    </td>
                   @* <td>
                       @Html.ActionLink(@Html.DisplayFor(modelItem => complainDTO.ComplainNumber).ToString(), "Details", "Complain", 
                         new { compId = complainDTO.Id },null)
                        
                    </td>*@
                    <td>
                        @Html.ActionLink(@Html.DisplayFor(modelItem => complainDTO.Employee.FirstName).ToString(), "Details", "Employee", 
                         new { empId = complainDTO.Employee.IdEncrypted },null)
                      
                    </td>
                    <td>
                         @Html.ActionLink(@Html.DisplayFor(modelItem => complainDTO.Employee.Visa.SponsorFullNameShort).ToString(), "Details", "Visa", 
                         new { visaId = complainDTO.Employee.Visa.IdEncrypted },null)
                    
                    </td>
                     @*  <td>
                        @Html.DisplayFor(modelItem => complainDTO.Employee.Visa.Sponsor.Address.Mobile)
                    </td>*@
                    <td style="text-align: center;font-weight: bolder">
                        @Html.DisplayFor(modelItem => complainDTO.DaysPassed)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => complainDTO.ComplainTypeDescription)
                    </td>
                         <td>
                        @Html.DisplayFor(modelItem => complainDTO.Status)
                    </td>
       
                    <td style="text-align: center;" class="hidden-print hidden-phone">
                        @Html.ActionLink("View", "Details", "Complain", new { compId = complainDTO.IdEncrypted }, new { @Class = "btn btn-info btn-small" })
@*                        *@
                        @switch (complainDTO.Status)
                        {
                            case ComplainStatusTypes.OnProcess:
                            case ComplainStatusTypes.ReOpened:
                            case ComplainStatusTypes.Opened:
                                @Html.ActionLink("Edit", "Edit", "Complain", new {compId = complainDTO.IdEncrypted}, new {@Class = "btn btn-primary btn-small",@style="margin-right: 5px;"})
                                @Html.ActionLink("Add Remark", "AddRemark", "Complain", new { compId = complainDTO.IdEncrypted }, new { @Class = "btn btn-warning btn-small",@style="margin-right: 5px;" })
                                @Html.ActionLink("Close", "CloseComplain", "Complain", new {compId = complainDTO.IdEncrypted}, new {@Class = "btn btn-danger btn-small"})
                                break;
                            case ComplainStatusTypes.Confirmed:
                                @Html.ActionLink("Delete", "Delete", "Complain", new {compId = complainDTO.IdEncrypted}, new {@Class = "btn btn-danger btn-small"})
                                break;
                            case ComplainStatusTypes.Closed:
                                @Html.ActionLink("Confirm", "Confirm", "Complain", new {compId = complainDTO.IdEncrypted}, new {@Class = "btn btn-success btn-small",@style="margin-right: 5px;"})
                                @Html.ActionLink("Re-Open", "ReOpen", "Complain", new {compId = complainDTO.IdEncrypted}, new {@Class = "btn btn-warning btn-small"})
                                break;
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
    
    <ul class="pager">
        <li style="display:@ViewData["prevDisabled"]; " class="hidden-print">
            @Ajax.ActionLink("← Previous", "Index", "Complain",
                new
                {
                    processStatusId = @ViewData["processStatusId"],
                    searchText = @ViewData["SearchText"],
                    page = @ViewData["Page"],
                    pageSize = @ViewData["PageSize"],
                    ptype = -1,
                    categoryId = @ViewData["CategoryId"],
                    filterByQuantity = @ViewData["FilterByQuantity"]
                }, new AjaxOptions
                {
                    HttpMethod = "GET",
                    InsertionMode = InsertionMode.Replace,
                    UpdateTargetId = "table_id",
                    LoadingElementId = "spinner"
                })
        </li>

        <li>
            <span>Page @ViewData["Page"] of @ViewData["totalPages"] </span>
        </li>

        <li style="display:@ViewData["nextDisabled"]; " class="hidden-print">
            @Ajax.ActionLink("Next →", "Index", "Complain",
                new
                {
                    processStatusId = @ViewData["processStatusId"],
                    searchText = @ViewData["SearchText"],
                    page = @ViewData["Page"],
                    pageSize = @ViewData["PageSize"],
                    ptype = 1,
                    categoryId = @ViewData["CategoryId"],
                    filterByQuantity = @ViewData["FilterByQuantity"]
                }, new AjaxOptions
                {
                    HttpMethod = "GET",
                    InsertionMode = InsertionMode.Replace,
                    UpdateTargetId = "table_id",
                    LoadingElementId = "spinner"
                }, new { @style = "width: 106px;" })
        </li>
    </ul>

</div>

PinnaFace.Web/Views/Shared/_employee.cshtml
@using PinnaFace.Core.Enumerations
@using PinnaFace.Core.Models
@model IEnumerable<PinnaFace.Core.Models.EmployeeDTO>

@{
    var imagePath = "../Images/EP9086232_Short.jpg";
}
<div id="table_id">
    <div id="spinner">
    </div>
    
    @if (@Model.Any())
    {
        <div class="alert alert-info fade in @ViewData["ItemSearchHidden"]">
            <button type="button" class="close" data-dismiss="alert">×</button>
            @MvcHtmlString.Create(@ViewData["ItemSearch"].ToString())
        </div>

        <div>
            <h4 style="margin-top: 3px;">@ViewData["EmployeeStatusHeader"] Employees</h4> 
            <p> (@ViewData["totalNumber"]) Employee(s) found</p>
        </div>

        <table class="table table-striped table-condensed table-hover " id="table_id2">

            <tr>
                <th>@Html.DisplayNameFor(model => model.SerialNumber)
                </th>
                <th>Photo</th>
                <th>Agency
                </th>
                <th>Agent
                </th>
                <th>Name
                </th>
                <th>Passport No.
                </th>
                 @*<th>@Html.DisplayNameFor(model => model.Sex)
                </th>
                <th>Age
                </th>*@
                <th>@Html.DisplayNameFor(model => model.VisaDetail)
                </th>
                <th>@Html.DisplayNameFor(model => model.CurrentStatus)
                </th>
                <th style="text-align: center; width: 350px;" class="hidden-print"></th>
            </tr>

            <tbody>
                @foreach (EmployeeDTO employeeDto in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => employeeDto.SerialNumber)
                        </td>
                        <td>
                            
                            @if (employeeDto.Photo != null) 
                            {
                                imagePath = "../Content/Images/" + employeeDto.Photo.RowGuid + ".jpg";
                            }
                            <a href="~/Employee/Details?empId=@employeeDto.IdEncrypted&processStatusId=0&searchText=@ViewData["searchText"]&ageCategoryId=@ViewData["ageCategoryId"]&religionId=@ViewData["religionId"]&languageId=@ViewData["languageId"]&experienceId=@ViewData["experienceId"]">
                                    </a><img  src="@Url.Content(imagePath)" alt="Photo" name="shortPhoto" onError="this.onerror=null;this.src='/images/BlankShort.jpg';"
                                          style="border-radius: 5px; height: 60px; width: 75px;"/>
                        </td>
                        <td>
                            @if (employeeDto.Agency != null)
                            {
                                @Html.ActionLink(@Html.DisplayFor(
                                    modelItem => employeeDto.AgencyName).ToString(), "AgencyDetail", "Home",
                                    new {agencyId = employeeDto.Agency.IdEncrypted}, null)
                            }
                        </td>
                        <td>
                            @if (employeeDto.Agent != null)
                            {
                                @Html.ActionLink(@Html.DisplayFor(
                                    modelItem => employeeDto.AgentName).ToString(), "AgentDetail", "Home",
                                    new {agentId = employeeDto.Agent.IdEncrypted}, null)
                            }
                        </td>
                        <td>
                            @Html.ActionLink(@Html.DisplayFor(
                                modelItem => employeeDto.FirstName).ToString(), "Details", "Employee",
                                new {empId = employeeDto.IdEncrypted,processStatusId=@ViewData["processStatusId"]}, null)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => employeeDto.PassportNumber)
                        </td>
                @*        <td>
                            @Html.DisplayFor(modelItem => employeeDto.Sex)
                        </td>*@
               
                        <td>
                            @if(employeeDto.Visa!=null){
                                @Html.ActionLink(@Html.DisplayFor(modelItem => employeeDto.VisaDetail).ToString(), "Details", "Visa",
                                    new {visaId = employeeDto.Visa.IdEncrypted}, null)}
                            else{ @Html.Display("-") }
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => employeeDto.StatusString)
                        </td>
                
                        <td style="text-align: center;" class="hidden-print">
                            @Html.ActionLink("View", "Details", "Employee", new {empId = employeeDto.IdEncrypted}, new {@Class = "btn btn-info btn-small"})
                           
                            @if (employeeDto.Visa == null)
                            {
                                @*Html.ActionLink("Edit", "Edit", "Employee", new {empId = employeeDto.IdEncrypted}, new {@Class = "btn btn-warning btn-small", @style = "margin-right:5px;"})*@
                                @Html.ActionLink("Assign Visa", "Assign", "Employee", new {empId = employeeDto.IdEncrypted}, new {@Class = "btn btn-success btn-small", @style = "margin-right:5px;"})
                                @*Html.ActionLink("Delete", "Delete", "Employee", new {empId = employeeDto.IdEncrypted}, new {@Class = "btn btn-danger btn-small"})
                                 Html.ActionLink("Agreement", "AgreementDocument", "Report", 
                                    new {empId = employeeDto.IdEncrypted}, 
                                    new {@Class = "btn btn-warning btn-small", @target="_blank", @style = "margin-right:5px;"})
                                *@
                            }
                            @if (employeeDto.Visa != null && (employeeDto.CurrentStatus == ProcessStatusTypes.VisaAssigned || employeeDto.CurrentStatus == ProcessStatusTypes.OnProcess))
                            {
                               
                                @Html.ActionLink("Detach Visa", "Detach", "Visa",
                                    new {visaId = employeeDto.Visa.IdEncrypted},
                                    new {@Class = "btn btn-danger btn-small", @style = "margin-right:5px;"})
                                
                            }
                            @if (employeeDto.CurrentStatus == ProcessStatusTypes.OnGoodCondition)
                            {
                                @Html.ActionLink("Add Complain", "Create", "Complain", new {empId = employeeDto.IdEncrypted}, new {@Class = "btn btn-primary btn-small"})
                            }

                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <ul class="pager">
            <li style="display: @ViewData["prevDisabled"];" class="hidden-print">
                @Ajax.ActionLink("← Previous", "Index", "Employee",
                    new
                    {
                        processStatusId = @ViewData["processStatusId"],
                        searchText = @ViewData["SearchText"],
                        page = @ViewData["Page"],
                        pageSize = @ViewData["PageSize"],
                        ptype = -1,
                        categoryId = @ViewData["CategoryId"],
                        filterByQuantity = @ViewData["FilterByQuantity"]
                    }, new AjaxOptions
                    {
                        HttpMethod = "GET",
                        InsertionMode = InsertionMode.Replace,
                        UpdateTargetId = "table_id",
                        LoadingElementId = "spinner"
                    })
            </li>

            <li>
                <span>Page @ViewData["Page"] of @ViewData["totalPages"] </span>
            </li>

            <li style="display: @ViewData["nextDisabled"];" class="hidden-print">
                @Ajax.ActionLink("Next →", "Index", "Employee",
                    new
                    {
                        processStatusId = @ViewData["processStatusId"],
                        searchText = @ViewData["SearchText"],
                        page = @ViewData["Page"],
                        pageSize = @ViewData["PageSize"],
                        ptype = 1,
                        categoryId = @ViewData["CategoryId"],
                        filterByQuantity = @ViewData["FilterByQuantity"]
                    }, new AjaxOptions
                    {
                        HttpMethod = "GET",
                        InsertionMode = InsertionMode.Replace,
                        UpdateTargetId = "table_id",
                        LoadingElementId = "spinner"
                    }, new {@style = "width:106px;"})
            </li>
        </ul>
    }
    else
    {
        <h4 class="error"> no employee found...</h4>
    }
</div>