PinnaFace.Web/Controllers/DownloadController.cs
using System;
using System.IO;
using System.Net;
using System.Web.Mvc;
using PinnaFace.Core;

namespace PinnaFace.Web.Controllers
{
    [Authorize]
    public class DownloadController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Download(string file)
        {
            //try
            //{
            //    const string ftphost = "198.38.83.167";
            //    var ftpfilepath = "/pinnaface.com/downloads/" + file;
            //    var ftpfullpath = "ftp://" + ftphost + ftpfilepath;

            //    using (var request = new WebClient())
            //    {
            //        request.Credentials = DbCommandUtil.GetNetworkCredential();// new NetworkCredential("munahan1", "hani1212");

            //        byte[] fileData = request.DownloadData(ftpfullpath);

            //        var response = new FileContentResult(fileData, "application/exe")
            //        {
            //            FileDownloadName = file
            //        };
            //        return response;
            //    }
            //}
            //catch (WebException e)
            //{
            //    String status = ((FtpWebResponse)e.Response).StatusDescription;
            //    return View("Error",
            //        new HandleErrorInfo(new Exception(status), "Download",
            //            "Download"));
            //}

            return View("Index");
        }


        //public ActionResult Download(string file)
        //{
        //    string ftphost = "198.38.83.167";
        //    string ftpfilepath = "/munahan1/pinnaface.com/downloads/" + file;

        //    string ftpfullpath = "ftp://" + ftphost + ftpfilepath;

        //    if (!System.IO.File.Exists(ftpfullpath))
        //    {
        //        return HttpNotFound(ftpfullpath);
        //    }

        //    var fileBytes = System.IO.File.ReadAllBytes(ftpfullpath);
        //    var response = new FileContentResult(fileBytes, "application/octet-stream")
        //    {
        //        FileDownloadName = file // "loremIpsum.pdf"
        //    };
        //    return response;
        //}
        //private void Download(string file)
        //{
        //    string url = "ftp://198.38.83.167/munahan1/pinnaface.com/downloads/";// "ftp://ftp.example.com/directory/to/download/";
        //    try
        //    {
        //        string uri = url + "/" + file;
        //        Uri serverUri = new Uri(uri);
        //        if (serverUri.Scheme != Uri.UriSchemeFtp)
        //        {
        //            return;
        //        }
        //        FtpWebRequest request = (FtpWebRequest)WebRequest.Create(url + "/" + file);
        //        request.UseBinary = true;
        //        request.Method = WebRequestMethods.Ftp.DownloadFile;
        //        request.Credentials = new NetworkCredential("munahan1", "hani1212");
        //        request.KeepAlive = false;
        //        request.UsePassive = false;
        //        FtpWebResponse response = (FtpWebResponse)request.GetResponse();
        //        Stream responseStream = response.GetResponseStream();
        //        FileStream writeStream = new FileStream(localDestnDir + "\\" + file, FileMode.Create);
        //        int Length = 2048;
        //        Byte[] buffer = new Byte[Length];
        //        int bytesRead = responseStream.Read(buffer, 0, Length);
        //        while (bytesRead > 0)
        //        {
        //            writeStream.Write(buffer, 0, bytesRead);
        //            bytesRead = responseStream.Read(buffer, 0, Length);
        //        }
        //        writeStream.Close();
        //        response.Close();
        //    }
        //    catch (WebException wEx)
        //    {
        //        //MessageBox.Show(wEx.Message, "Download Error");
        //    }
        //    catch (Exception ex)
        //    {
        //        //MessageBox.Show(ex.Message, "Download Error");
        //    }
        //}

        
    }
}

PinnaFace.Web/Views/Download/Index.cshtml
@{
    ViewBag.Title = "Downloads ";
}

<h3>Downloads</h3>
<div class="clear-fix"></div>
<hr/>


<h5 style="margin-top: 25px;">PinnaFace Downloads </h5>
<hr style="margin-top: 5px; margin-bottom: 5px;"/>
<ul>
    <li>
        @Html.ActionLink("PinnaFace Simple Edition", "Download", "Download", new {file = "SimpleEdition"}, null)
    </li>
    <li>
        @Html.ActionLink("PinnaFace Advanced Edition", "Download", "Download", new {file = "AdvancedEdition"}, null)
    </li>
    <li>
        @Html.ActionLink("PinnaFace EnjazOnly Edition", "Download", "Download", new {file = "EnjazOnly"}, null)
    </li>
    <li>
        @Html.ActionLink("PinnaFace Web Sync Extension", "Download", "Download", new {file = "WebSync"}, null)
    </li>

</ul>



<h5 style="margin-top: 25px;">Prerequisite Downloads for All OS </h5>
<hr style="margin-top: 5px; margin-bottom: 5px;"/>
<ul>
     <li><a href="https://download.microsoft.com/download/B/A/4/BA4A7E71-2906-4B2D-A0E1-80CF16844F5F/dotNetFx45_Full_setup.exe">Dot Net Framework 4.5</a></li>
   @* <li>
        @Html.ActionLink("Dot Net Framework 4.5", "Download", "Download", new {file = "DotNet"}, null)
    </li>*@
    <li>
        @Html.ActionLink("AspNet WebPages Setup", "Download", "Download", new {file = "AspNetWebPages"}, null)
    </li>
    @*<li>
        @Html.ActionLink("Report Viewer", "Download", "Download", new {file = "ReportViewer.exe"}, null)
    </li>*@
</ul>


<h5 style="margin-top: 25px;">Prerequisite Downloads for 64 Bit OS </h5>
<hr style="margin-top: 5px; margin-bottom: 5px;"/>
<ul>
     <li>
        @Html.ActionLink("Crystal Reports Runtime 64 bit", "Download", "Download", new {file = "CRRuntime64"}, null)
    </li>
    <li>
        @Html.ActionLink("Sql Server Compact Edition 4.0 64 bit", "Download", "Download", new {file = "SSCE64"}, null)
    </li>
        <li>
        @Html.ActionLink("Amharic Library 64 bit", "Download", "Download", new {file = "Amharic64"}, null)
    </li>
@*    <li><a>Crystal Reports Runtime 64 bit</a></li>
    <li><a>Sql Server Compact Edition 4.0 64 bit </a></li>
    <li><a>Amharic Library 64 bit</a></li>*@
</ul>

<h5 style="margin-top: 25px;">Prerequisite Downloads for 32 Bit OS </h5>
<hr style="margin-top: 5px; margin-bottom: 5px;"/>
<ul>
     <li>
        @Html.ActionLink("Crystal Reports Runtime 32 bit", "Download", "Download", new {file = "CRRuntime32"}, null)
    </li>
    <li>
        @Html.ActionLink("Sql Server Compact Edition 4.0 32 bit", "Download", "Download", new {file = "SSCE32"}, null)
    </li>
        <li>
        @Html.ActionLink("Amharic Library 32 bit", "Download", "Download", new {file = "Amharic32"}, null)
    </li>
    @*<li><a>Crystal Reports Runtime 32 bit</a></li>
    <li><a>Sql Server Compact Edition 4.0 32 bit </a></li>
    <li><a>Amharic Library 32 bit</a></li>*@
</ul>


<script type="text/javascript">

    $('#downloadmenu').addClass('active');
</script>